TESTS=

.PHONY: default all clean

default: all

all:
	make -C AveragingFilter_01_07_15
	make -C Mandelbrot_12_17_14
	make -C BlackScholes_12_17_14
	make -C DCT_01_07_15

clean:
	make -C AveragingFilter_01_07_15 clean
	make -C Mandelbrot_12_17_14 clean
	make -C BlackScholes_12_17_14 clean
	make -C DCT_01_07_15 clean
